displayName=Meteor Reporter
author=CoreyUK
description=Report crashed stars and see active reports shared by other plugin users
tags=meteor,shooting,star,mining,report,crowdsource
version=
plugins=com.meteorreporter.MeteorReporterPlugin
build=standard
