displayName=Meteor Reporter
author=CoreyUK
description=Report crashed stars and see active stars and telescope scouting shared by other plugin users
tags=meteor,shooting,star,mining,report,scout,telescope,crowdsource
version=
plugins=com.meteorreporter.MeteorReporterPlugin
build=standard
